### ISSUE TITLE
Enable m3u8 extension

### ISSUE THREAD

**Issue by norter** [YouPHPTube/YouPHPTube#1700]
Hello,

First congratulate you for the work done.

I'm trying to enable the **m3u8** extension to be able to upload video with this format, but I can not find a way to do it, just upload it in mp4 format.

I'm not looking to stream in real time, if not in the videos. For example:
```
https://demo.youphptube.video/videos/_YPTuniqid_5c5d54bf720d43.32956716/hd/index.m3u8
```

Thank you,
a greeting

<img width="1648" alt="Captura de pantalla 2019-04-30 a las 11 44 02" src="https://user-images.githubusercontent.com/234262/56953902-cabbe780-6b3d-11e9-90f3-45fd6aa710af.png">

**Comment by DanielnetoDotCom** [comment]
Hi, 

sorry but is not clear to me what you want.

do you want to convert your uploaded videos into HLS (m3u8) format?

if yes, maybe you are looking for the HLS plugin, what is not for sale yet because it only supports a self-hosted (in your server drive) streamer. 

So this plugin does not support S3 or B2 or FTP storages.

if you are self-hosting your videos and want the HLS plugin please email me at developer@youphptube.com

**Comment by norter** [comment]
Great, I write to you then by private,

Thank you,
a greeting
