### ISSUE TITLE
embed iframe

### ISSUE THREAD

**Issue by pgioia** [YouPHPTube/YouPHPTube#1742]
when i embed a iframe, for example 

<iframe
                        style="max-width: 100%; max-height: 100%;"
                        src="http://xxxx.xxxx.xxx.xx/plugin/Live/?c=encoderA&embed=1autoplay=1?autoplay=1"
                        frameborder="0" allowfullscreen="allowfullscreen" class="YouPHPTubeIframe"></iframe>

or 

<iframe
                        style="max-width: 100%; max-height: 100%;"
                        src="http://xxxx.xxxx.xxx.xx/plugin/Live/?c=encoderA&embed=1autoplay=1"
                        frameborder="0" allowfullscreen="allowfullscreen" class="YouPHPTubeIframe"></iframe>

the function autoplay only works in Microsoft Edge and Microsoft Internet Explorer 11.
In Firefox i need clic in play button to run streaming.

In Safari and Google Chrome not working the streaming directrly 

my version of phptube is  YouPHPTube 5.3!

**Comment by DanielnetoDotCom** [comment]
Google Chrome and Safari have recently updated their autoplay policies in order to improve their user experience. As a result, these browsers now control the rules around when a video will autoplay. Here is a breakdown of Chrome's rules:

- Autoplay with sound will be allowed when:

1. The user has interacted with your domain in some way (click, etc.)
2. On desktop, the user has previously played video with sound
3. On mobile, the user has added the site to his or her homescreen

- Muted autoplay is always allowed on Google Chrome.

In order to enable muted autoplay of the Dailymotion player, ensure that the embedded player has both the autoplay and mute settings enabled (autoplay=1&mute=1).
On Safari Desktop, autoplay can be enabled by updating the autoplay setting for the website embedding the player accordingly. If this rule is set to "Never Auto-Play," showcased below, autoplay will not be enabled for your site. 

https://faq.dailymotion.com/hc/en-us/articles/360000102908-Browser-rules-that-determine-autoplay

**Comment by pgioia** [comment]
i Modified the embed and remains the same

<iframe style="max-width: 100%; max-height: 100%;"
                        src="http://agtube.aldeaglobal.net.ar/plugin/Live/?c=encoderA&embed=1&autoplay=1&mute=1" frameborder="0" allowfullscreen="allowfullscreen" class="YouPHPTubeIframe"></iframe>

I copy my code so you can see it and try it if you have time

my version of phptube is YouPHPTube 5.3!

do you help me

**Comment by DanielnetoDotCom** [comment]
As I post above this is not an iframe issue, is your browser.

Also, I really recommend you to update your version to 7.*

**Comment by pgioia** [comment]
first of all thanks for your reply
I have updated the site to the YouPHPTube 7.2 version as you suggested it
I have also included the parameters autoplay=1&mute=1 in the iframe as they indicated

<iframe style="max-width: 100%; max-height: 100%;" src="http://plugin/Live/?c=encoderA&embed=1&mute=1&autoplay=1" frameborder="0" allowfullscreen="allowfullscreen" class="YouPHPTubeIframe"></iframe>

And the result is the same.

I attach an image
![captura](https://user-images.githubusercontent.com/36860320/58276718-869fb980-7d6e-11e9-8b73-457b95042170.png)

**Comment by DanielnetoDotCom** [comment]
Hi @pgioia 

As I wrote above there is nothing you can do to guarantee your video will autoplay on an iframe

Google Chrome and Safari have recently updated their autoplay policies in order to improve their user experience. As a result, these **browsers now control the rules around when a video will autoplay**.

**Comment by pgioia** [comment]
ok. Thank

In agreement. Thank you

e if I wanted to embed the transmission directly

http: // xxxxxxx: 8080 / live / 5cdc1dbf903f0 / index.m3u8

What should I keep in mind? with having videojs and videojs-hls on the site would be enough?

**Comment by DanielnetoDotCom** [comment]
I guess if you just use videojs 7+ it will work

**Comment by SergejGrin** [comment]
Hello!
I looked at all the messages about inserting iframr code from my AVideo v.8.0 site to other sites, but I could understand why this code does not work.
Maybe I need to include some kind of plugin or buy the necessary one?
My website: http://tube.wakeupnow.info
Embed cod: 
`<iframe width="640" height="360" style="max-width: 100%;max-height: 100%; border:none;" src="http://tube.wakeupnow.info/videoEmbed/c-1991-" frameborder="0" allowfullscreen="allowfullscreen" allow="autoplay" scrolling="no">iFrame is not supported!</iframe> `
What needs to be done or what am I doing wrong?
Thank you in advance for your reply.
![Embed1](https://user-images.githubusercontent.com/59236880/71524398-aaf7e180-28cd-11ea-890b-29456204f252.png)

**Comment by DanielnetoDotCom** [comment]
Your embed code looks fine

In what site are you inserting the code?

FYI your site is http and you are probably inserting in a https

You must make your site https to make it work in https sites

**Comment by SergejGrin** [comment]
I have my own server on which virtual servers are installed. Port 443 is dedicated to a web server with sites, and the video site is on a separate virtual server. There is only one network channel, for this reason a video site can use port 80. I would not want to install a video site together with web sites.
On this page, I inserted the code from my site and below from YouTube.
https://wakeupnow.info/ru/2-uncategorised/3110-video
