### ISSUE TITLE
VideoHLS plugin

### ISSUE THREAD

**Issue by Donnerstein** [YouPHPTube/YouPHPTube#1850]
Hello,
I saw a plugin on the demo site, VideoHLS (VideoHLS).
Also the local encoder has this option.
I have not been able to find and buy this plugin from their listings.
Where do you get this?

Yours sincerely

**Comment by DanielnetoDotCom** [comment]
Hi

The VideoHLS generate an encrypted HLS video with adaptive bitrate in 3 resolutions.
so the resolutionSwitcher plugin is unnecessary for HLS videos because the resolution is automatically switched. 

the HLS is a plugin that is not on the market yet. It is not on the market because does not support the plugins S3 or B2 or FTP storage yet.

but if you are self-hosting the videos on your own drive you should be fine.

the HLS plugins I sell only for selected users. If you are interested in buying it please email me at developer@youphptube.com.

**Comment by bobbyrabbit** [comment]
Pleased to say I am using the HLS plugin on my dedicated server. Highly recommended.

**Comment by DanielnetoDotCom** [comment]
@bobbyrabbit thanks for the review :)

**Comment by Donnerstein** [comment]
Thanks for the quick replies.

**Comment by Donnerstein** [comment]
For the HLS Encoded Videos the download function does not work under the videos. The m3u8 file is displayed and called up when clicked. Do I have a bug, or is the download of HLS videos not supported?

**Comment by DanielnetoDotCom** [comment]
download HLS is not supported.

Download works only for MP4 and WEBM files.

**Comment by Donnerstein** [comment]
thx
