### ISSUE TITLE
Ads location only "ALL"

### ISSUE THREAD

**Issue by illias1** [YouPHPTube/YouPHPTube#1953]
Hello!

Even though I activated the location plugin and clicked on "install tables" there is no any choice of location to select...

<img width="1236" alt="plugin selected" src="https://user-images.githubusercontent.com/54018215/62993052-da630000-be90-11e9-8f98-aec29547be5b.png">

<img width="381" alt="Location" src="https://user-images.githubusercontent.com/54018215/62992988-940da100-be90-11e9-99e0-5480cae14abe.png">

Any ideas? 
Thank you!

**Comment by akhilleusuggo** [comment]
I'm not sure about this , but maybe you need to install the plugin ''User_Location (User_Location)'' . Never tested it , but this one is the only one that can detect the location of the user , otherwise there's no way to determine where the viewer is coming from . Please try it , and leave a feedback :)

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo is correct

**Comment by illias1** [comment]
It works! Thank you:)
