### ISSUE TITLE
website and script security

### ISSUE THREAD

**Issue by yzhuan19** [YouPHPTube/YouPHPTube#2043]
@DanielnetoDotCom I only found the cached website when I was paying for the $69.99 service using paypal and searched the email address associated with your paypal on google. I just want to make sure that the publicly available script is safe to use, and the personal information would be safely encrypted and stored so no one can access it. If you block me and don't explain, I am not sure what is real and what happened and would like to request a refund of all the plugins I have purchased.

**Comment by yzhuan19** [comment]
![image](https://user-images.githubusercontent.com/55461074/65072102-12081080-d945-11e9-9482-42b72128453b.png)

**Comment by DanielnetoDotCom** [comment]
This code is opensource and if there is any malicious code I am sure the comunity would already found it.

so there is no risk on it, since it is not a blackbox.

this site was made by someone (crazy) that want to use YouPHPTube for porn websites, and I forbid it.

he got upset and create a site to scam me and my family.

I appreciate you to preserve me.

**Comment by yzhuan19** [comment]
@DanielnetoDotCom Do you have a gmail account I can add to communicate via google drive (chat/edits)? Thanks.

**Comment by DanielnetoDotCom** [comment]
Hi, when we need a faster communication we can schedule a time by email and we meet in the site chat.
https://www.youphptube.com/
