### ISSUE TITLE
Encoder plugin stop at 77%

### ISSUE THREAD

**Issue by guitarpound** [YouPHPTube/YouPHPTube#2213]
Hi,

I tried testing to do live streaming for 4 hrs.
But after stop streaming.
The Encoder plugin stop at 77%.

It working well.  If I streaming for short time such as 5-10 min.

My YouPHPTube install on Cloud server CPU: 2 Core / RAM : 2GB.
Is it because Hardware spec not enough.  Right?

Thanks

**Comment by XemTube-TV** [comment]
How should the RAM be?
There is a script calculation..., your maximum file size can be only 50% of your RAM memory because the script needs to copy files between locations and handles it on the virtual memory.

In Example, if you want to upload a 4GB file you will need to have at least 8 GB Ram on the server otherwise you will have a Memory Leaks - Allowed memory size of # bytes exhausted error.

https://github.com/YouPHPTube/YouPHPTube/wiki/YouPHPTube-hadware-requirements

**Comment by guitarpound** [comment]
Thanks
