### ISSUE TITLE
Says my IP address is still the same as it was 

### ISSUE THREAD

**Issue by ucmafialtd** [YouPHPTube/YouPHPTube#2256]
@DanielnetoDotCom hey brotha I am wondering, why it says my IP address is still on the same server as it was on turnkey ? Thought new one was built and can't find it anywhere

**Comment by ucmafialtd** [comment]
Yo what's up

**Comment by JedMeister** [comment]
He @ucmafialtd - are you not planning on using TurnKey anymore? If not, that's fine, no hard feelings or any of that. Especially considering that you had such a crappy run trying to get things up and running...

Although as you say, the TurnKey server is still running (so is still costing you money on AWS) and you are still on the TurnKey free trial which will expire in a few days. Please hit me up via support@turnkeylinux.org so I can help you shut your server and account down so that you don't get hit with fees!

Re getting your domain to migrate to a new server, you'll need to adjust the nameservers with your domain registrar to point to whatever new nameservers you are using. Otherwise, you'll need to create an A record to point to your server's IP.

**Comment by ucmafialtd** [comment]
Yo Daniel what's up am I not finding the new server that you said you made of is there not one
![348636425](https://user-images.githubusercontent.com/53587701/68828380-4c96dc80-065a-11ea-8a00-f349ab5c234f.png)

**Comment by DanielnetoDotCom** [comment]
I will email you your server credentials.
